### ISSUE TITLE
How to put something as data in fulfillment

### ISSUE THREAD

**Issue by wieczorek1990** [xVir/api-ai-facebook#1]
https://github.com/api-ai/api-ai-facebook/blob/master/src/app.js#L39
How do I define `fulfillment.data`?

**Comment by xVir** [comment]
Hi, @wieczorek1990 
You have to use webhook feature for this.
Please take a look at the sample https://github.com/xVir/apiai-python-webhook/blob/master/app.py#L125 and documentation https://docs.api.ai/docs/webhook

Thanks!

**Comment by wieczorek1990** [comment]
:+1:
